services:
  bentopdf:
    image: bentopdf/bentopdf
    container_name: bentopdf
    restart: unless-stopped
    init: true
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.services.pdf.loadbalancer.server.port: 8080
      traefik.http.routers.pdf.entrypoints: https
      traefik.http.routers.pdf.rule: Host(`${FQDN}`)
      traefik.http.routers.pdf.middlewares: oidc-auth@file,my-geoblock@file
networks:
  proxy:
    external: true
x-dockge:
  urls:
    - https://${FQDN}
