services:
  otterwiki:
    image: redimp/otterwiki:2
    container_name: otterwiki
    restart: unless-stopped
    init: true
    volumes:
      - data:/app-data
    environment:
      SITE_NAME: Wiki
      DISABLE_REGISTRATION: true
      READ_ACCESS: REGISTERED
      WRITE_ACCESS: REGISTERED
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.services.otterwiki.loadbalancer.server.port: 80
      traefik.http.routers.otterwiki.entrypoints: https
      traefik.http.routers.otterwiki.rule: Host(`${FQDN}`)
volumes:
  data: {}
networks:
  proxy:
    external: true

