services:
  miniflux-client:
    image: atareao/miniflux-client:latest
    container_name: miniflux-client
    init: true
    restart: unless-stopped
    environment:
      MATRIX_ROOM: ${MATRIX_ROOM}
      MATRIX_TOKEN: ${MATRIX_TOKEN}
      MATRIX_URL: ${MATRIX_URL}
      MAX_ENTRIES: ${MAX_ENTRIES}
      MINIFLUX_CATEGORIES: ${MINIFLUX_CATEGORIES}
      MINIFLUX_TOKEN: ${MINIFLUX_TOKEN}
      MINIFLUX_URL: ${MINIFLUX_URL}
      MODEL_API_KEY: ${MODEL_API_KEY}
      MODEL_NAME: ${MODEL_NAME}
      MODEL_URL: ${MODEL_URL}
      SLEEP_TIME: ${SLEEP_TIME}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TELEGRAM_THREAD_ID: ${TELEGRAM_THREAD_ID}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      RUST_LOG: DEBUG
      MODEL_DESCRIPTION: Eres un asistente especializado en noticias internacionales
      MODEL_PROMPT: 'Analiza todas las noticias proporcionadas y genera un JSON de la
        siguiente forma: `{"news": [{"url": "<url>", "title": "<title>",
        "summary": "<summary>"}]}`, reemplazando `<url>`, `<title>` y
        `<summary>` por la url, el título traducido al español y un resumen
        explicando la noticia en español. Tiene que ir todo en una única línea.
        No indiques que me devuelves un JSON, simplemente devuelve el JSON como
        te indiqué.'

