version: '3.7'
services:
  homer:
    image: b4bz/homer
    container_name: homer
    init: true
    restart: unless-stopped
    volumes:
      - ./assets:/www/assets
    user: 1000:1000
    enviroment:
      INIT_ASSETS: 1
