version: '3'
services:
  nginx:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.grafana.loadbalancer.server.port=8080
      - traefik.http.routers.nginx.entrypoints=web
      - traefik.http.routers.nginx.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.nginx-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.nginx.middlewares=nginx-https-redirect
      - traefik.http.routers.nginx-secure.entrypoints=websecure
      - traefik.http.routers.nginx-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.nginx-secure.tls=true
      - traefik.http.routers.nginx-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true
