services:
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    restart: unless-stopped
    init: true
    volumes:
      - memos:/var/opt/memos
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.services.memos.loadbalancer.server.port: 5230
      traefik.http.routers.memos.entrypoints: https
      traefik.http.routers.memos.rule: Host(`${FQDN}`)

volumes:
  memos: {}

networks:
  proxy:
    external: true
