iservices:
  memos:
    image: neosmemo/memos:latest
    init: true
    container_name: memos
    volumes:
      - memos
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.memos.loadbalancer.server.port=5230
      - traefik.http.routers.memos.entrypoints=https
      - traefik.http.routers.memos.rule=Host(`${FQDN}`)
    restart: unless-stopped

volumes:
  memos: {}

networks:
  proxy:
    external: true
