services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    init: true
    volumes:
      - beszel_data:/beszel_data
      - beszel_socket:/beszel_socket
    networks:
      - internal
      - proxy
    environment:
      - DISABLE_PASSWORD_AUTH=true
    labels:
      traefik.enable: true
      traefik.http.services.beszel.loadbalancer.server.port: 8090
      traefik.http.routers.beszel.rule: Host(`${FQDN}`)
      traefik.http.routers.beszel.entrypoints: https
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    init: true
    volumes:
      - beszel_agent_data:/var/lib/beszel-agent
      - beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: ${KEY}
      TOKEN: ${TOKEN}
      HUB_URL: http://beszel:8090
    networks:
      - internal
volumes:
  beszel_agent_data: {}
  beszel_data: {}
  beszel_socket: {}
networks:
  internal: {}
  proxy:
    external: true
x-dockge:
  urls:
    - https://${FQDN}

