services:
  uptime_kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime_kuma
    restart: unless-stopped
    init: true
    volumes:
      - data:/app/data
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.services.uptime_kuma.loadbalancer.server.port: 3001
      traefik.http.routers.uptime_kuma-secure.entrypoints: https
      traefik.http.routers.uptime_kuma-secure.rule: Host(`${FQDN}`)
volumes:
  data: {}
networks:
  proxy:
    external: true
x-dockge:
  urls:
    - https://${FQDN}
