version: '3.3'

services:

  uptime_kuma:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.uptime_kuma.loadbalancer.server.port=3001
      - traefik.http.routers.uptime_kuma-secure.entrypoints=https
      - traefik.http.routers.uptime_kuma-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.uptime_kuma-secure.tls=true
      - traefik.http.routers.uptime_kuma-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true
