version: '3.5'

services:

  photoprism:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.photoprism.loadbalancer.server.port=2342
      - traefik.http.routers.photoprism.entrypoints=web
      - traefik.http.routers.photoprism.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.photoprism-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.photoprism.middlewares=photoprism-https-redirect
      - traefik.http.routers.photoprism-secure.entrypoints=websecure
      - traefik.http.routers.photoprism-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.photoprism-secure.tls=true
      - traefik.http.routers.photoprism-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true
